version: "3.1"

services:
  frontend:
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - .env
    build: ./../frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  backend:
    container_name: backend
    env_file:
      - .env
    build: ./../backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
